easy_admin:
  site_name: '<img src="/admin/images/logo.png">'
  list:
    max_results: 10
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@VichUploader/Form/fields.html.twig'
      - '@AdminLTE/layout/default-layout.html.twig'
    assets:
      favicon: '/config/images/logo.png'
      css:
        - '/admin/css/custom.css'
      js:

    menu:

      - { label: 'Configurations' }
      - NetSuiteConfiguration
      - RevelConfiguration
      - { label: 'Schedular and History' }
      - Scheduler
      - NetsuiteToRevelHistory
      - RevelToNetsuiteHistory
      - SyncHistory
      - { label: 'Users' }
      - User
      - Roles



  entities:

    User:
      class: App\Entity\User
      controller: App\Controller\UserAdminController
      form: {fields: [username, email, role, password,isActive]}
    Roles:
      class: App\Entity\Role

    NetSuiteConfiguration:
      label: 'NetSuite Configuration'
      search:
        fields: ['name', 'key1', 'key2']
      class: App\Entity\NetSuiteConfiguration
      form: {fields: [name,apiEndpoint,key1,key2,key3,key4]}
      list: {help: 'NetSuite API Configuration.', actions: [ {name: show, icon: info-circle, label: Show}], fields: [name,apiEndpoint,key1,key2,key3,key4], sort: id}

    RevelConfiguration:
      label: 'Revel Configuration'
      class: App\Entity\RevelConfiguration
      form: {fields: [name,apiEndpoint,key1,key2,key3,key4]}
      list: {help: 'Revel API Configuration.', actions: [ {name: show, icon: info-circle, label: Show}], fields: [name,apiEndpoint,key1,key2,key3,key4], sort: id}

    NetsuiteToRevelHistory:
      class: App\Entity\NetsuiteToRevelHistory
      disabled_actions: ['new']
      label: 'Netsuite To Revel History'
      form: {fields: [{ property: 'ranTime', format: 'j/n/Y' },status,error]}
      list: {help: 'Netsuite To Revel History.', actions: [ {name: show, icon: info-circle, label: Show}], fields: [ranTime,status,error], sort: id}

    RevelToNetsuiteHistory:
      label: 'Revel To Netsuite History'
      disabled_actions: ['new']
      class: App\Entity\RevelToNetsuiteHistory
      form: {fields: [ranTime,status,error]}
      list: {help: 'Revel To Netsuite History.', actions: [ {name: show, icon: info-circle, label: Show}], fields: [ranTime,status,error], sort: id}

    Scheduler:
      class: App\Entity\Scheduler
      form: {fields: [name,description,interval_time]}
      list: {help: 'Most Recent sync history!', actions: [ 'search', {name: show, icon: info-circle, label: Show}], fields: [name,last_ran_time,interval_time,is_active], sort: id}

    SyncHistory:
      class: App\Entity\SyncHistory
      #search:
      #  fields: ['source', 'destination', 'transaction_record']
      label: 'Scheduler History'
      #disabled_actions: ['new']
      form: {fields: [source,destination,transaction_record,is_success,error,created_at]}
      list: {help: 'Most Recent Scheduler history!', actions: [ {name: show, icon: info-circle, label: Show}], fields: [source,destination,transaction_record,{ property: 'is_success', type: 'boolean' },error,created_at], sort: id}
