<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0hxBwDd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0hxBwDd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0hxBwDd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0hxBwDd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0hxBwDd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '0hxBwDd',
    'container.build_id' => '81fe8cd5',
    'container.build_time' => 1546075489,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0hxBwDd');
