<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\UploadImageAction' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/UploadImageAction.php';

return $this->services['App\Controller\UploadImageAction'] = new \App\Controller\UploadImageAction(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->privates['api_platform.validator'] ?? $this->load('getApiPlatform_ValidatorService.php')));
